export const CHAT_ACTIONS = {
    SET_USER:'SET_USER',
    SET_USERS:'SET_USERS',
    SET_MESSAGES:'SET_MESSAGES',
    SET_MESSAGE:'SET_MESSAGE',
    PREPEND_MESSAGES:'PREPEND_MESSAGES',
    SET_GROUP:'SET_GROUP',
    REFETCH:'REFETCH',
};